export {default as Login} from './common/login.js';
export {default as Rules} from './student/rules.js';
export {default as Quiz} from './student/quiz.js';
export {default as Summary} from './student/summary.js';
export {default as Registers} from './student/student_register.js';
export {default as Landing} from './common/landing.js';
export {default as teacherDash} from './teacher/teacher_dashboard.js';
export {default as Scores} from './teacher/scores_display.js';
export {default as Questions} from './teacher/question.js';
export {default as StudentCredGen} from './teacher/student_cred_gen.js';
export {default as Registert} from './teacher/teacher_register.js';
export {default as ExamChoice} from './student/examChoice.js';
export {default as PaperSettingsPage} from './teacher/paper_settings.js'