export {default as Header} from './Header/Header.js';
export {default as Footer} from './Footer/Footer.js';
export {default as Login} from './Login/Login.js';
export {default as Register} from './Register/Register.js';
export {default as Landing} from './Landing/Landing.js';
export {default as Rules} from './Rules/Rules.js';
export {default as Quiz} from './Quiz/Quiz.js';
export {default as Timer} from './Timer/Timer.js';
export {default as Summary} from './Summary/Summary.js';
export {default as Private} from './private-route/PrivateRoute.js'